name: Run the DW CLI

on:
  push:
    branches: [ main ]
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Install DataWeave CLI
        run: |
          curl -L https://github.com/mulesoft-labs/data-weave-cli/releases/download/v1.0.34/dw-1.0.34-Linux -o dw.zip
          unzip dw.zip -d $HOME/.dw/
          echo "$HOME/.dw/bin" >> "$GITHUB_PATH"
      - name: Test DW CLI
        run: dw help
      - name: Run DW script
        run: |
          dw run -f files-to-run/script/$(ls files-to-run/script) -i payload=files-to-run/input/$(ls files-to-run/input) 2>&1 | tee output
      - name: Upload result file
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output