name: Run the DW CLI

on:
  push:
    branches: [ main ]
  workflow_call:

jobs:
  run:
    runs-on: macos-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 11
      - name: Install DW CLI
        run: |
          brew tap mulesoft-labs/data-weave
          brew install dw
      - name: Test DW CLI
        run: dw help
      - name: Run DW script
        run: |
          dw run -f $(ls files-to-run/script) -i payload=$(files-to-run/input) > output
      - name: Upload result file
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output